[package]
name = "dither"
version = "0.3.3"
authors = ["Efron Licht <efron.python@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A ditherer for PNG images"
repository= "https://gitlab.com/efronlicht/dither"

[dependencies]
structopt = "0.2"
image = "0.21.0"
[dev-dependencies]
rand = "0.6.5"
